import type {
  CourseBranch,
  CourseCategory,
  CourseFormat,
  CourseItem,
  CourseLevel,
  CourseSchedule,
  DayAbbrev,
} from "../types/course.types";

export const COURSE_LEVEL_FILTERS = ["All", "A1-A2", "B1-B2", "C1-C2"] as const;

export const COURSE_MONTHS = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
] as const;

export const COURSE_FORMATS = ["All", "On-site", "Online"] as const;

export const COURSE_CATEGORIES = ["Standard", "Intensive", "Conversation"] as const;

export const COURSE_BRANCHES = [
  "Maadi",
  "Zamalek",
  "New Cairo",
  "Heliopolis",
] as const satisfies readonly CourseBranch[];

export const COURSE_DAYS = [
  "Sun",
  "Mon",
  "Tue",
  "Wed",
  "Thu",
  "Fri",
  "Sat",
] as const satisfies readonly DayAbbrev[];

export const COURSE_SCHEDULES = [
  "Morning (9:00 - 12:00)",
  "Evening (18:00 - 21:00)",
] as const satisfies readonly CourseSchedule[];

type CourseSeed = {
  id: number;
  badge: string;
  priceValue: number;
  title: string;
  description: string;
  weeks: number;
  startLabel: string;
  sessions: number;
  sessionMinutes: number;
  daysList: readonly DayAbbrev[];
  daysLabel: string;
  category: CourseCategory;
  branch: CourseBranch;
  level: CourseLevel;
  schedules: readonly CourseSchedule[];
  startMonth: string;
  format: CourseFormat;
  recommended?: boolean;
};

const COURSE_SEEDS: CourseSeed[] = [
  {
    id: 1,
    badge: "A1.1 Beginner",
    priceValue: 800,
    title: "German Foundation",
    description:
      "Start your journey with basic phrases and essential grammar for daily life in Austria.",
    weeks: 8,
    startLabel: "Oct 15",
    sessions: 24,
    sessionMinutes: 90,
    daysList: ["Mon", "Wed"],
    daysLabel: "Mon & Wed",
    category: "Standard",
    branch: "Maadi",
    level: "A1-A2",
    schedules: ["Evening (18:00 - 21:00)"],
    startMonth: "Oct",
    format: "On-site",
    recommended: true,
  },
  {
    id: 2,
    badge: "A1.2 Elementary",
    priceValue: 950,
    title: "German Intensive A1.2",
    description:
      "Accelerate your progress with immersive sessions focused on real-world communication.",
    weeks: 6,
    startLabel: "Nov 4",
    sessions: 18,
    sessionMinutes: 120,
    daysList: ["Tue", "Thu"],
    daysLabel: "Tue & Thu",
    category: "Intensive",
    branch: "Zamalek",
    level: "A1-A2",
    schedules: ["Morning (9:00 - 12:00)"],
    startMonth: "Nov",
    format: "On-site",
    recommended: true,
  },
  {
    id: 3,
    badge: "B1.1 Intermediate",
    priceValue: 1200,
    title: "Conversational German",
    description:
      "Build fluency through guided discussions, role-play, and cultural context.",
    weeks: 10,
    startLabel: "Sep 20",
    sessions: 30,
    sessionMinutes: 90,
    daysList: ["Mon", "Wed", "Fri"],
    daysLabel: "Mon, Wed & Fri",
    category: "Conversation",
    branch: "Heliopolis",
    level: "B1-B2",
    schedules: ["Evening (18:00 - 21:00)"],
    startMonth: "Sep",
    format: "On-site",
    recommended: true,
  },
  {
    id: 4,
    badge: "A2.1 Pre-Intermediate",
    priceValue: 900,
    title: "Everyday German Skills",
    description:
      "Navigate shopping, transport, and social situations with confidence.",
    weeks: 8,
    startLabel: "Oct 8",
    sessions: 24,
    sessionMinutes: 90,
    daysList: ["Sun", "Tue"],
    daysLabel: "Sun & Tue",
    category: "Standard",
    branch: "Heliopolis",
    level: "A1-A2",
    schedules: ["Morning (9:00 - 12:00)"],
    startMonth: "Oct",
    format: "On-site",
  },
  {
    id: 5,
    badge: "B2.1 Upper Intermediate",
    priceValue: 1400,
    title: "Professional German",
    description:
      "Master workplace vocabulary, presentations, and formal correspondence.",
    weeks: 12,
    startLabel: "Jan 12",
    sessions: 36,
    sessionMinutes: 90,
    daysList: ["Wed", "Fri"],
    daysLabel: "Wed & Fri",
    category: "Intensive",
    branch: "Heliopolis",
    level: "B1-B2",
    schedules: ["Evening (18:00 - 21:00)"],
    startMonth: "Jan",
    format: "Online",
  },
  {
    id: 6,
    badge: "A1.1 Beginner",
    priceValue: 750,
    title: "German Starter Online",
    description:
      "Live online classes with interactive exercises — learn from anywhere.",
    weeks: 8,
    startLabel: "Feb 3",
    sessions: 24,
    sessionMinutes: 75,
    daysList: ["Mon", "Wed"],
    daysLabel: "Mon & Wed",
    category: "Standard",
    branch: "New Cairo",
    level: "A1-A2",
    schedules: ["Evening (18:00 - 21:00)"],
    startMonth: "Feb",
    format: "Online",
  },
  {
    id: 7,
    badge: "B1.2 Intermediate",
    priceValue: 1100,
    title: "German for Travelers",
    description:
      "Practical language for exploring Austria — hotels, dining, and directions.",
    weeks: 6,
    startLabel: "Mar 10",
    sessions: 18,
    sessionMinutes: 90,
    daysList: ["Sat"],
    daysLabel: "Saturday",
    category: "Conversation",
    branch: "New Cairo",
    level: "B1-B2",
    schedules: ["Morning (9:00 - 12:00)"],
    startMonth: "Mar",
    format: "On-site",
  },
  {
    id: 8,
    badge: "C1.1 Advanced",
    priceValue: 1600,
    title: "Academic German Mastery",
    description:
      "Prepare for university-level reading, writing, and academic discourse.",
    weeks: 14,
    startLabel: "Apr 7",
    sessions: 42,
    sessionMinutes: 90,
    daysList: ["Tue", "Thu"],
    daysLabel: "Tue & Thu",
    category: "Intensive",
    branch: "New Cairo",
    level: "C1-C2",
    schedules: ["Evening (18:00 - 21:00)"],
    startMonth: "Apr",
    format: "On-site",
  },
  {
    id: 9,
    badge: "A2.2 Elementary",
    priceValue: 850,
    title: "German Grammar Workshop",
    description:
      "Strengthen sentence structure and verb conjugation through focused drills.",
    weeks: 6,
    startLabel: "May 5",
    sessions: 18,
    sessionMinutes: 90,
    daysList: ["Mon", "Thu"],
    daysLabel: "Mon & Thu",
    category: "Standard",
    branch: "Maadi",
    level: "A1-A2",
    schedules: ["Morning (9:00 - 12:00)"],
    startMonth: "May",
    format: "On-site",
  },
  {
    id: 10,
    badge: "B1.1 Intermediate",
    priceValue: 1050,
    title: "Business German Basics",
    description:
      "Email etiquette, meetings, and negotiations in a German business context.",
    weeks: 8,
    startLabel: "Jun 2",
    sessions: 24,
    sessionMinutes: 90,
    daysList: ["Wed"],
    daysLabel: "Wednesday",
    category: "Intensive",
    branch: "Maadi",
    level: "B1-B2",
    schedules: ["Evening (18:00 - 21:00)"],
    startMonth: "Jun",
    format: "Online",
  },
  {
    id: 11,
    badge: "A1.1 Beginner",
    priceValue: 780,
    title: "German for Families",
    description:
      "Family-friendly pace with cultural activities for parents and children.",
    weeks: 10,
    startLabel: "Jul 8",
    sessions: 20,
    sessionMinutes: 60,
    daysList: ["Sat", "Sun"],
    daysLabel: "Sat & Sun",
    category: "Standard",
    branch: "Zamalek",
    level: "A1-A2",
    schedules: ["Morning (9:00 - 12:00)"],
    startMonth: "Jul",
    format: "On-site",
  },
  {
    id: 12,
    badge: "C1.2 Advanced",
    priceValue: 1750,
    title: "ÖSD Exam Preparation",
    description:
      "Targeted training for C1 certification with mock exams and feedback.",
    weeks: 10,
    startLabel: "Aug 11",
    sessions: 30,
    sessionMinutes: 90,
    daysList: ["Mon", "Wed", "Fri"],
    daysLabel: "Mon, Wed & Fri",
    category: "Intensive",
    branch: "Zamalek",
    level: "C1-C2",
    schedules: ["Evening (18:00 - 21:00)"],
    startMonth: "Aug",
    format: "On-site",
  },
  {
    id: 13,
    badge: "A2.1 Pre-Intermediate",
    priceValue: 880,
    title: "Pronunciation & Listening",
    description:
      "Fine-tune Austrian accent and comprehension with audio-rich exercises.",
    weeks: 6,
    startLabel: "Sep 15",
    sessions: 18,
    sessionMinutes: 90,
    daysList: ["Tue", "Wed"],
    daysLabel: "Tue & Wed",
    category: "Conversation",
    branch: "Maadi",
    level: "A1-A2",
    schedules: ["Evening (18:00 - 21:00)"],
    startMonth: "Sep",
    format: "On-site",
  },
  {
    id: 14,
    badge: "B2.2 Upper Intermediate",
    priceValue: 1350,
    title: "Media & Culture German",
    description:
      "Analyze Austrian films, news, and literature while expanding vocabulary.",
    weeks: 8,
    startLabel: "Oct 22",
    sessions: 24,
    sessionMinutes: 90,
    daysList: ["Thu", "Fri"],
    daysLabel: "Thu & Fri",
    category: "Conversation",
    branch: "Heliopolis",
    level: "B1-B2",
    schedules: ["Evening (18:00 - 21:00)"],
    startMonth: "Oct",
    format: "Online",
  },
  {
    id: 15,
    badge: "A1.2 Elementary",
    priceValue: 820,
    title: "German Fast Track",
    description:
      "Condensed curriculum for motivated learners who want rapid progress.",
    weeks: 5,
    startLabel: "Nov 18",
    sessions: 20,
    sessionMinutes: 120,
    daysList: ["Mon", "Tue", "Wed", "Thu"],
    daysLabel: "Mon – Thu",
    category: "Intensive",
    branch: "New Cairo",
    level: "A1-A2",
    schedules: ["Morning (9:00 - 12:00)"],
    startMonth: "Nov",
    format: "On-site",
  },
  {
    id: 16,
    badge: "B1.2 Intermediate",
    priceValue: 1150,
    title: "German Writing Skills",
    description:
      "Essays, formal letters, and creative writing with instructor feedback.",
    weeks: 8,
    startLabel: "Dec 1",
    sessions: 24,
    sessionMinutes: 90,
    daysList: ["Mon", "Wed"],
    daysLabel: "Mon & Wed",
    category: "Standard",
    branch: "Zamalek",
    level: "B1-B2",
    schedules: ["Evening (18:00 - 21:00)"],
    startMonth: "Dec",
    format: "On-site",
  },
  {
    id: 17,
    badge: "C1.1 Advanced",
    priceValue: 1550,
    title: "Debate & Discussion Club",
    description:
      "Advanced speakers practice argumentation on current Austrian topics.",
    weeks: 6,
    startLabel: "Jan 20",
    sessions: 12,
    sessionMinutes: 120,
    daysList: ["Wed"],
    daysLabel: "Wednesday",
    category: "Conversation",
    branch: "Maadi",
    level: "C1-C2",
    schedules: ["Evening (18:00 - 21:00)"],
    startMonth: "Jan",
    format: "On-site",
  },
  {
    id: 18,
    badge: "A1.1 Beginner",
    priceValue: 720,
    title: "German Basics Online",
    description:
      "Evening online sessions perfect for working professionals.",
    weeks: 10,
    startLabel: "Feb 10",
    sessions: 20,
    sessionMinutes: 75,
    daysList: ["Tue", "Thu"],
    daysLabel: "Tue & Thu",
    category: "Standard",
    branch: "Heliopolis",
    level: "A1-A2",
    schedules: ["Evening (18:00 - 21:00)"],
    startMonth: "Feb",
    format: "Online",
  },
  {
    id: 19,
    badge: "B2.1 Upper Intermediate",
    priceValue: 1280,
    title: "German for Healthcare",
    description:
      "Medical terminology and patient communication for healthcare workers.",
    weeks: 10,
    startLabel: "Mar 3",
    sessions: 30,
    sessionMinutes: 90,
    daysList: ["Mon", "Fri"],
    daysLabel: "Mon & Fri",
    category: "Intensive",
    branch: "Zamalek",
    level: "B1-B2",
    schedules: ["Morning (9:00 - 12:00)"],
    startMonth: "Mar",
    format: "On-site",
  },
  {
    id: 20,
    badge: "A2.2 Elementary",
    priceValue: 860,
    title: "Weekend German Immersion",
    description:
      "Intensive weekend blocks with cultural workshops and group activities.",
    weeks: 8,
    startLabel: "Apr 12",
    sessions: 16,
    sessionMinutes: 180,
    daysList: ["Sat", "Sun"],
    daysLabel: "Sat & Sun",
    category: "Intensive",
    branch: "Maadi",
    level: "A1-A2",
    schedules: ["Morning (9:00 - 12:00)"],
    startMonth: "Apr",
    format: "On-site",
  },
  {
    id: 21,
    badge: "B1.1 Intermediate",
    priceValue: 1000,
    title: "German Café Conversations",
    description:
      "Relaxed small-group sessions over coffee — practice without pressure.",
    weeks: 6,
    startLabel: "May 14",
    sessions: 12,
    sessionMinutes: 90,
    daysList: ["Wed", "Thu"],
    daysLabel: "Wed & Thu",
    category: "Conversation",
    branch: "New Cairo",
    level: "B1-B2",
    schedules: ["Evening (18:00 - 21:00)"],
    startMonth: "May",
    format: "On-site",
  },
  {
    id: 22,
    badge: "C1.2 Advanced",
    priceValue: 1680,
    title: "Literary German",
    description:
      "Read and discuss classic and contemporary Austrian literature in German.",
    weeks: 12,
    startLabel: "Jun 9",
    sessions: 24,
    sessionMinutes: 90,
    daysList: ["Tue"],
    daysLabel: "Tuesday",
    category: "Conversation",
    branch: "Heliopolis",
    level: "C1-C2",
    schedules: ["Evening (18:00 - 21:00)"],
    startMonth: "Jun",
    format: "Online",
  },
  {
    id: 23,
    badge: "A1.2 Elementary",
    priceValue: 790,
    title: "German for Teens",
    description:
      "Engaging curriculum designed for students aged 14–18 with games and projects.",
    weeks: 8,
    startLabel: "Jul 15",
    sessions: 24,
    sessionMinutes: 75,
    daysList: ["Mon", "Wed"],
    daysLabel: "Mon & Wed",
    category: "Standard",
    branch: "New Cairo",
    level: "A1-A2",
    schedules: ["Morning (9:00 - 12:00)"],
    startMonth: "Jul",
    format: "On-site",
  },
  {
    id: 24,
    badge: "B2.2 Upper Intermediate",
    priceValue: 1320,
    title: "Corporate German Training",
    description:
      "Customized business modules for teams relocating to German-speaking countries.",
    weeks: 10,
    startLabel: "Aug 4",
    sessions: 30,
    sessionMinutes: 90,
    daysList: ["Mon", "Wed", "Fri"],
    daysLabel: "Mon, Wed & Fri",
    category: "Intensive",
    branch: "Zamalek",
    level: "B1-B2",
    schedules: ["Morning (9:00 - 12:00)", "Evening (18:00 - 21:00)"],
    startMonth: "Aug",
    format: "On-site",
  },
];

function mapSeedToCourse(seed: CourseSeed): CourseItem {
  return {
    id: seed.id,
    badge: seed.badge,
    price: `${seed.priceValue.toLocaleString()} EGP`,
    priceValue: seed.priceValue,
    title: seed.title,
    description: seed.description,
    duration: `${seed.weeks} Weeks | Start: ${seed.startLabel}`,
    sessions: `${seed.sessions} Sessions (${seed.sessionMinutes} min each)`,
    days: seed.daysLabel,
    daysList: seed.daysList,
    category: seed.category,
    branch: seed.branch,
    level: seed.level,
    schedules: seed.schedules,
    startMonth: seed.startMonth,
    format: seed.format,
    recommended: seed.recommended,
  };
}

export const COURSES: CourseItem[] = COURSE_SEEDS.map(mapSeedToCourse);

export const TOTAL_COURSE_COUNT = COURSES.length;

export const COURSE_DETAIL = {
  id: 1,
  breadcrumbTitle: "German Foundation (A1.1)",
  badge: "A1.1 Beginner",
  title: "German Foundation",
  subtitle:
    "Master the essentials of the German language in a structured, immersive environment.",
  price: "800 EGP",
  priceNote: "/ total",
  taxNote: "VAT Included",
  seatsLeft: "12 Seats Left",
  features: ["Beginner Friendly", "Certificate Included", "Native Instructors"],
  stats: [
    { label: "Duration", value: "8 Weeks" },
    { label: "Sessions", value: "24 Sessions" },
    { label: "Format", value: "In-person" },
    { label: "Class Size", value: "Max 12 students" },
  ],
  booking: [
    {
      title: "Starts Oct 15, 2024",
      description: "Enrollment ends Oct 10",
    },
    {
      title: "Mon & Wed, 18:00",
      description: "2.5 hours per session",
    },
    {
      title: "Zamalek Branch",
      description: "Classroom 402",
    },
  ],
  about:
    "Our German Foundation (A1.1) course is designed for absolute beginners who wish to embark on their journey with the German language. We follow the Common European Framework of Reference for Languages (CEFR), ensuring that you receive a globally recognized standard of education. This intensive program focuses on practical communication skills, allowing you to handle everyday situations in a German-speaking environment. From introducing yourself to navigating public transport, you will build a solid foundation in grammar, vocabulary, and pronunciation.",
  learningOutcomes: [
    {
      title: "Real Conversations",
      description:
        "Practice dialogues for everyday situations like shopping and dining.",
    },
    {
      title: "Grammar Foundations",
      description: "Understand sentence structure and essential verb conjugations.",
    },
    {
      title: "Official Certificate",
      description:
        "Earn a course completion certificate recognized by EU institutions.",
    },
  ],
  curriculum: [
    "Week 1-2: Introductions & The Basics",
    "Week 3-4: Daily Life & Time",
  ],
  details: [
    { label: "Start Date", value: "October 15, 2024" },
    { label: "End Date", value: "December 10, 2024" },
    { label: "Schedule", value: "Mon & Wed, 18:00 - 20:30" },
    { label: "Location", value: "Central Cairo Branch (Zamalek)" },
  ],
  faqs: [
    "Do I need any prior knowledge?",
    "Is the course book included in the price?",
  ],
};

export const RELATED_COURSES = [
  {
    id: 2,
    image: "/blog1.png",
    badge: "A1.2 Intermediate",
    title: "German Intensive A1.2",
    price: "950 EGP",
  },
  {
    id: 3,
    image: "/event.png",
    badge: "B1.1 Advanced",
    title: "Conversational German",
    price: "1,200 EGP",
  },
  {
    id: 4,
    image: "/hero.jpg",
    badge: "B2 Business",
    title: "Business German Basics",
    price: "1,500 EGP",
  },
];
